### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by smontode24** [fanegg/UV-Volumes#1]
Hey, first of all I wanted to say that the results look amazing, great work!
Are you planning to release pretrained models? I would like to do some experiments. I was processing the dataset for training but Densepose's code is pretty old and I don't know if you have tried using the most recent version from detectron2.

Best,
Sergio

**Comment by fanegg** [comment]
Unfortunately, we did not save the pre-trained models or try to use detectron 2, but we think it should be feasible and easier to output IUV images with detectron 2.

**Comment by smontode24** [comment]
Okay @fanegg, thanks anyway
