### ISSUE TITLE
Problems that occur during code run

### ISSUE THREAD

**Issue by JACKYLUO1991** [fanegg/UV-Volumes#3]
When i run **python3 train_net.py --cfg_file configs/zju_mocap_exp/313.yaml exp_name zju313 resume False output_depth True**,  it shows **NaN or Inf found in input tensor** error.

**Comment by fanegg** [comment]
It looks weird. Maybe you should check the input data. Did you build your dataset as described in [INSTALL.md](https://github.com/fanegg/UV-Volumes/blob/main/INSTALL.md#get-the-pre-defined-uv-unwrap-in-densepose)?

**Comment by JACKYLUO1991** [comment]
@fanegg It should be caused by the brackets in the image name conversion. Another issue has arisen that：
 File "lib/datasets/dataset.py", line 163, in __getitem__
    **i_gt = np.eye(25)[dp[:, :, 0]][..., (1 - int(cfg.use_bg)) :].astype(np.float32)
IndexError: index 52 is out of bounds for axis 0 with size 25**

**Comment by fanegg** [comment]
Hi, @JACKYLUO1991, did you use the IUV images outputted by [DensePose](https://github.com/facebookresearch/DensePose/blob/main/GETTING_STARTED.md#inference-with-pretrained-models)? DensePose defines IUV images for 24 body parts, so the value of `I` in the IUV images should be in the range of **[0, 23]**, but the `I` at `IndexError: index 52 is out of bounds for axis 0 with size 25` seems not to be defined by [DensePose](https://github.com/facebookresearch/DensePose/blob/main/GETTING_STARTED.md#inference-with-pretrained-models). Would you like to refer to the [example](https://drive.google.com/file/d/13zTTWSHdi9h3H5BVSHsqTHZC8GFQEeM6/view) we provided, where the IUV image is at `data_example/densepose/Camera_B1/000000_IUV.png`?

**Comment by JACKYLUO1991** [comment]
@fanegg 
![image](https://user-images.githubusercontent.com/21237742/230573721-d976d4e8-61e1-4eb6-835d-276c1fddd1d5.png)
The output graph looks like this, but it's not the green one you gave, what's the reason for that?

**Comment by fanegg** [comment]
You might change the code to adapt to this new type of IUV image or use the original version of [DensePose](https://github.com/facebookresearch/DensePose/blob/main/GETTING_STARTED.md#inference-with-pretrained-models).

**Comment by swanilee** [comment]
@JACKYLUO1991 Hello, do you solve this? I also have same problem with this.
